name: puzzix_site
description: "Puzzix — Casual sliding puzzle game"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   # ⬅️ ajouter ceci

  go_router: ^14.2.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/screenshots/ # mets tes images ici (optionnel)
